### ISSUE TITLE
Standardize usage of single quote and double quote

### ISSUE THREAD

**Issue by jpbullalayao** [jpbullalayao/sendbird-python#10]
Currently, the code base uses both single quotes and double quotes for strings. Look for what the best convention is (see PEP, etc.) and choose a single convention to be used on 100% of the strings

**Comment by Wittionary** [comment]
After looking at some forum threads and documentation, the "best" practice I could find is if you're going to have strings with apostrophes in them, use double quotes. Aside from that, it's all preference given the interpreter sees them the same way.
From the little code I've looked over, it looks to be mostly double quotes.

@jpbullalayao Would you like me to move forward with getting all of the strings to use double quotes or are you leaning towards single quotes?

**Comment by jpbullalayao** [comment]
@Wittionary Hey sorry didn't see this right away, if that's the case let's change them all to double quotes! The only other option is to go with single quotes and then escaping potential apostrophes inside the strings, but that's more work than using double quotes everywhere. Can you create a new branch and PR for converting all single quote usage to double quotes? 

Don't be worried about having to test functionality given it's just changing quotation syntax.

**Comment by Wittionary** [comment]
@jpbullalayao Sure thing! Working on it now.
